DEFINE VARIABLE maxKey AS INTEGER NO-UNDO.
DEFINE VARIABLE nextKey AS INTEGER NO-UNDO.
DEFINE VARIABLE ud100aKey AS INTEGER NO-UNDO.
ASSIGN maxKey = 100.
ASSIGN nextKey = 1.
FOR EACH UD100a:
	FIND FIRST ttUD100a WHERE ttUD100a.Company = UD100a.Company NO-ERROR.
	IF AVAILABLE ttUD100a THEN DO:
		ASSIGN ud100aKey = INTEGER(UD100a.ChildKey1).
		IF ud100aKey > maxKey THEN DO:
			ASSIGN maxKey = ud100aKey.
		END.
	END.
	ASSIGN nextKey = maxKey + 1.
	ttUD100a.ChildKey1 = STRING(nextKey).
END. 
